apiVersion: batch/v1
kind: CronJob

metadata:
  name: demo-cronjob
  namespace: devops-lab

spec:
  schedule: "* * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - sh
            - -c
            - echo CronJob Executed

          restartPolicy: Never
